from .models import RAICollection

from wagtail.core import hooks



class RAIDocumentOnDemand:
    """
    A class for documents that are generated by the server on demand
    """
    # An identifier which identifies the subclass
    identifier = None

    # a view that is called by ajax that generates the document
    createview = None

    # the related model
    model = None


class RAIBaseCollection:
    collection_id = 'rai-files'
    collection_name = 'RAI Files'

    def get_path(self):
        mro = self.__class__.mro()
        mro.reverse()
        p = []
        for cls in mro:
            if hasattr(cls, 'collection_id'):
                p.append(cls.collection_id)
        return p

    def get_id(self):
        return '.'.join(self.get_path())

    def get_pk(self):
        rc = self.get_obj()
        return rc.pk

    def get_obj(self):
        rc = RAICollection.objects.get(name = self.get_id())
        return rc
    
    def register(self):
        print('Registering: {}'.format(self.get_id()))
        collection_id = ''
        parent_collection = None
        for path in self.get_path():
            if collection_id != '':
                collection_id += '.'
            collection_id += path
            try:
                parent_collection = RAICollection.objects.get(name = collection_id)
            except RAICollection.DoesNotExist:
                collection = RAICollection(
                    display_name = self.collection_name,
                    name = collection_id
                )
                if not parent_collection:
                    collection = RAICollection(
                        name = collection_id,
                        display_name = self.collection_name
                    )
                    RAICollection.add_root(instance = collection)
                else:
                    parent_collection.add_child(instance = collection)
                parent_collection = collection
        # Register with wagtail
        @hooks.register('rai_document_collection')
        def register_collection():
            return {self.get_id(): self}
        
class RAIDocumentCollection(RAIBaseCollection):
    """
    A class that generates a collection, if not already available
    """
    collection_name = 'Documents'
    collection_id = 'documents'

    # def get_path(self):
    #     path = super().get_path()
    #     path.append(self.collection_id)
    #     print (path)
    #     return path

    
            
def register_collection(Collection_class):
    collection = Collection_class()
    collection.register()
